###
### LOCAL
###

### generate a random question
GET http://localhost:5000/api/generate

### get the game modes
GET http://localhost:5000/api/modes

### create or get user
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "yonela"
}

### save user score to the leaderboard
POST http://localhost:5000/api/save
Content-Type: application/json

{
    "playerId": 1,
    "modeId": 3,
    "score": 30
}

### get the leaderboard
GET http://localhost:5000/api/leaderboard

###
### ONLINE http://theakatsuki.xyz/
###

### generate a random question
GET http://theakatsuki.xyz/api/generate

### get the game modes
GET http://theakatsuki.xyz/api/modes

### create or get user
POST http://theakatsuki.xyz/api/user
Content-Type: application/json

{
    "username": "yonela"
}

### save user score to the leaderboard
POST http://theakatsuki.xyz/api/save
Content-Type: application/json

{
    "playerId": 1,
    "modeId": 3,
    "score": 30
}

### get the leaderboard
GET http://theakatsuki.xyz/api/leaderboard