###
### LOCAL
###

### generate a random question
GET http://localhost:5000/api/generate

### generate on post
POST http://localhost:5000/api/generate
Content-Type: application/json

{
    "mode": "hard"
}

### get the game modes
GET http://localhost:5000/api/modes

### create or get user
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "yonela"
}

### save user score to the leaderboard
POST http://localhost:5000/api/save
Content-Type: application/json

{
    "playerId": 1,
    "modeId": 3,
    "score": 30
}

### get the leaderboard
GET http://localhost:5000/api/leaderboard

###
### ONLINE https://theakatsuki.xyz/
###

### generate a random question
GET https://theakatsuki.xyz/api/generate

### generate on post
POST https://theakatsuki.xyz/api/generate
Content-Type: application/json

{
    "mode": "medium"
}

### get the game modes
GET https://theakatsuki.xyz/api/modes

### create or get user
POST https://theakatsuki.xyz/api/user
Content-Type: application/json

{
    "username": "fanie"
}

### save user score to the leaderboard
POST https://theakatsuki.xyz/api/save
Content-Type: application/json

{
    "playerId": 1,
    "modeId": 3,
    "score": 30
}

### get the leaderboard
GET https://theakatsuki.xyz/api/leaderboard